// Auto-generated by deploy-and-export.js — do not edit manually.
// Deployed: 2026-06-23T20:57:06.234Z | Network: sepolia
// AjoCircle:        https://sepolia.etherscan.io/address/0x7B7E1c3D036C5C13382E8c4d675e7752D2b620b4
// RollaVault:       https://sepolia.etherscan.io/address/0x4fD9d162961D9aD355E0C779409E38ABa7Aa31e2
// UsernameRegistry: https://sepolia.etherscan.io/address/0xFb1643670eB349b1b6a77958685fBB743d7D2eA6

export const CONTRACT_ADDRESSES = {
  AJO_CIRCLE:        "0x7B7E1c3D036C5C13382E8c4d675e7752D2b620b4" as `0x${string}`,
  ROLLA_VAULT:       "0x4fD9d162961D9aD355E0C779409E38ABa7Aa31e2" as `0x${string}`,
  USERNAME_REGISTRY: "0xFb1643670eB349b1b6a77958685fBB743d7D2eA6" as `0x${string}`,
} as const;

export const TOKEN_ADDRESSES = {
  USDT: "0x7169D38820dfd117C3FA1f22a697dBA58d90BA06" as `0x${string}`,
  WETH: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14" as `0x${string}`,
} as const;

export const PROTOCOL_ADDRESSES = {
  UNISWAP_ROUTER: "0x3bFA4769FB09eefC5a80d6E87c3B9C650f7Ae48E" as `0x${string}`,
  UNISWAP_QUOTER: "0xEd1f6473345F45b75833fd55D5ADbEb76d79229" as `0x${string}`,
  AAVE_POOL:      "0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951" as `0x${string}`,
  CHAINLINK_ETH:  "0x694AA1769357215DE4FAC081bf1f309aDC325306" as `0x${string}`,
} as const;

export const CHAIN_ID = 11155111;
