// Auto-generated by deploy-and-export.js — do not edit manually.
// Deployed: 2026-06-25T13:38:34.338Z | Network: sepolia
// AjoCircle:        https://sepolia.etherscan.io/address/0x6bba73Fa725357faf03b660F6727799C6B529366
// RollaVault:       https://sepolia.etherscan.io/address/0x1Da5E825c273F173da45a0AF3aBf938DA0761342
// UsernameRegistry: https://sepolia.etherscan.io/address/0x2808324229e00C3Dc10BEe19fd8eb2Df24991eA5

export const CONTRACT_ADDRESSES = {
  AJO_CIRCLE:        "0x6bba73Fa725357faf03b660F6727799C6B529366" as `0x${string}`,
  ROLLA_VAULT:       "0x1Da5E825c273F173da45a0AF3aBf938DA0761342" as `0x${string}`,
  USERNAME_REGISTRY: "0x2808324229e00C3Dc10BEe19fd8eb2Df24991eA5" as `0x${string}`,
} as const;

export const TOKEN_ADDRESSES = {
  USDC: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238" as `0x${string}`,
  WETH: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14" as `0x${string}`,
} as const;

export const PROTOCOL_ADDRESSES = {
  UNISWAP_ROUTER: "0x3bFA4769FB09eefC5a80d6E87c3B9C650f7Ae48E" as `0x${string}`,
  UNISWAP_QUOTER: "0xEd1f6473345F45b75833fd55D5ADbEb76d79229" as `0x${string}`,
  AAVE_POOL:      "0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951" as `0x${string}`,
  CHAINLINK_ETH:  "0x694AA1769357215DE4FAC081bf1f309aDC325306" as `0x${string}`,
} as const;

export const CHAIN_ID = 11155111;
